### ISSUE TITLE
Team Member Bios and Images

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/nightingale#1]
For the funder of this project and also for marketing purposes, can everyone please provide:
- [x] a short bio about themselves, answering the questions below
- [x] a picture of themselves :)

It can be very informal (the bio and the image) and doesn't have to be long (no more than 100 words per point).

Questions:

**Comment by thejoefriel** [comment]
Here's Simons:

## A brief background on who you are:

Hi I’m Simon, 31 years old from Germany. I grew up in a lovely Bavarian village called Kirchehrenbach but moved to Berlin to study and start a semi-professional DJ career :)

## How did you get into coding?

While studying Natural Resource Management I was enrolled in some Geographic Information System courses involving some basic Python scripting. Later I made a couple of websites for own projects and later for other clients and really enjoyed it! After graduating from Uni I also worked as an environmental data scientist which meant that I had to collaborate with software developers to put our case study work into small Apps. Thats when I realised - I need to change careers!

## What made you join Founders & Coders?

I’ve heard about FAC because a friend was doing the program beforehand. He told me about FAC’s visions and ethics and I was blown away by the relation of coding and social impact and software development as a team based activity.

## What excites you about working on Tech for Better?

Having studied politics, economics and natural resource management I found myself being very conscious about the importance of improving social and environmental conditions. One of the most effective ways towards sustainable, positive change is the use of technology. Having recently graduated from Founders and Coders I am very eager to use my software development skills within the Tech for Better programme. I am sure that together we can make huge impact and I am very excited about the chance to work together with like minded developers in Gaza and the UK.

**Comment by thejoefriel** [comment]
Here's mine:

## A brief background on who you are:

Hi. My name's Joe, 31 years old from London. Before joining Founders & Coders and becoming a developer, I spent the past 9 years working in children's media and then digital advertising. 

## How did you get into coding?

Through my career I've worked on digital brands, from copywriting when I first started work through to leading the innovation and creation of a platform that would enable brands to identify and track influencers and then manage influencer campaigns. Throughout all of this I've worked closely with developers and always generally found myself more interested in what they were doing than my own work! 

I was increasingly doing coding on the side, working on little projects, and after reaching a certain level in my career at that time and not really being fulfilled, I realised that it was time to take the plunge!

## What made you join Founders & Coders?

I spent a long, LONG time looking through bootcamps, discussing with people who had gone through them of their experiences, trying to work out what would be best. However, a big focus for me has always been not just coding, but also getting the chance to use this in some way that has at least a small amount of net positive impact on the world. So when I finally came across FAC's ethos it just felt like the perfect fit. And that's before then learning more about just how amazing the course is, the peer-led learning environment and everything else that makes FAC great! 😄 

## What excites you about working on Tech for Better?

Having spent most of my career working where technology and young people intersect, I have seen first hand how powerful and increasingly integral a role technology plays in our lives. However, technology itself is amoral – it is up to us to use it in a responsible way that will help drive positive, sustainable change. Tech for Better is a truly unique and fantastic opportunity that connects like-minded developers – across the UK and Gaza – with people looking to address important social issues, to bring to life solutions through technology that can deliver real impact.  I am so excited to have the opportunity to be a part of Tech for Better and help it to continue to grow so we can help many more non-profits in the future.

**Comment by RamyAlshurafa** [comment]
## A brief background on who you are:

Hi, my name's **Ramy**; I am 26 years old. I was born in Gaza-Palestine. I attended Islamic University - Gaza. First, I studied Science for 2 years. Then, I studied Mechanical Engineering for one semester. After that, I studied Civil Engineering.
I graduated as a Civil Engineer then I received the Surveying and GIS Diploma. I worked for 2 years in these two fields.

## How did you get into coding?

Since previously I did not know much about coding or computer science, I never thought of it as an interest of mine. I studied 3 programs while at the University. When I studied MATLAB for my Engineering major, I found it very interesting and attracted me to the field. 

After I graduated, I was not satisfied with my jobs; after 2 years, I decided to go back to University and study Computer Engineering. Fortunately, I saw a post on Facebook for applications to the 4th cohort I GazaSkyGeeks, so I decided to apply. and I began coding.
## What made you join Founders & Coders?

I didn't hear about Founders and Coders before I enrolled in GazaSkyGeeks. However, I have found that it is a really amazing and exciting community. It changed my whole life forever. I was able to meet and work with some very talented developers. This experience has really sharpened my coding and personal skills.

## What excites you about working on Tech for Better?

I applied to work on Tech for Better so that I can have the opportunity to improve my technical skills. Working with remote clients and remote developers are invaluable experiences that will allow me to see how other developers think and to learn new techniques.

**Comment by AsalaKM** [comment]
## A brief background on who you are:

Hi, my name's **Asala**, 20 years old from Gaza-Palestine. I'm a 2018 graduate of E-business management from Khan Younis Training College.

## How did you get into coding?

Through my college education I've learned  the programming basics, web design, front end developing, asp.net basics and SQL database.
Before graduation, I've knew about GazaSkyGeeks programs through the workshop held at my college, and I was look very interested about it, specially which focus on coding and technical skills such as code academy program.
After graduating, I was satisfied with my skills. But because I'm still young, I did't want to stop learning, I always think that I should improve my skills: personal and technical.
So, I decided to apply for the fifth group in an academic program.

## What made you join Founders & Coders?

I know about Founders and Coders after I joined in code academy at  GazaSkyGeeks. Since then, I found that it is an awesome community, they have smart, talented, helpful people who offer the best support to young people.

## What excites you about working on Tech for Better?

My top interest in work and learning is work in teams, faced challenges, work in complex projects which offer opportunities for gaining new experiences and have fun :smile: . So, I applied to work on Tech for Better so that I can  have the opportunity to improve my technical skills. Working with remote clients and remote developers are height experiences that will allow me to see how other developers think and to learn new techniques. I also thrive on challenge. I am motivated about new challenges and tasks and always attempt to take original approaches to achieve success in all project.

**Comment by thejoefriel** [comment]
@RamyAlshurafa @AsalaKM - just a gentle nod to send across an image please of each of you? Feel free to email me if you don't want to attach it here :)

**Comment by RamyAlshurafa** [comment]
![img_6582](https://user-images.githubusercontent.com/34629478/51840764-97d33f00-2315-11e9-92ce-1e3931b47735.JPG)
I'm really sorry, I forgot about it

**Comment by thejoefriel** [comment]
Thanks @RamyAlshurafa . @AsalaKM - can you send yours tomorrow please?
